name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.207.121.144 >> ~/.ssh/known_hosts

      - name: Install Nginx on Server
        run: |
          ssh ${{ secrets.SSH_USER }}@18.207.121.144 "sudo apt update && sudo apt install -y nginx && sudo systemctl enable --now nginx"
