name: Deploy NGINX on Server

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.81.113.21 >> ~/.ssh/known_hosts

      - name: Install & Start NGINX on Server
        run: |
          ssh ubuntu@54.81.113.21 << 'EOF'
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
          EOF

      - name: Test NGINX
        run: ssh ubuntu@54.81.113.21 "curl -I http://54.81.113.21"
