name: Deploy Nginx Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nginx-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install and Start Nginx
        run: |
          sudo apt update
          sudo apt install -y nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx

      - name: Verify Nginx is Running
        run: |
          curl -I http://localhost | grep "200 OK"
