name: Install Nginx on multiple servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server_ip:
          - 54.234.227.52

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Known Hosts
        run: ssh-keyscan -H ${{ matrix.server_ip }} >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: ssh -v ubuntu@${{ matrix.server_ip }} "echo SSH Connection Successful"

      - name: Install Nginx on Server
        run: |
          ssh ubuntu@${{ matrix.server_ip }} 'sudo apt-get update && sudo apt-get install -y nginx'
