name: Install NGINX on AWS Server

on:
  push:
    branches:
      - main  # Adjust to your desired branch.

jobs:
  install_nginx:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository (optional if you need access to the code)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent and add private key
      - name: Set up SSH key with agent
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval $(ssh-agent -s)
          ssh-add private_key.pem

      # Step 3: Install NGINX on the AWS instance
      - name: Install NGINX on AWS server
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@54.234.227.52 << 'EOF'
            sudo apt-get update
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
          EOF

      # Step 4: Clean up private key file after usage
      - name: Clean up
        run: rm -f private_key.pem
