name: Deploy NGINX on EC2 using AWS SSM

on: [push, workflow_dispatch]

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: sudo apt install -y awscli

      - name: Install NGINX via AWS SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=MyServer" \
            --parameters "commands=['sudo apt update', 'sudo apt install -y nginx', 'sudo systemctl start nginx', 'sudo systemctl enable nginx']" \
            --region us-east-1 \
            --query "Command.CommandId" \
            --output text
