name: Install Nginx on Server

on:
  push:
    branches:
      - main  # Trigger this action on push to the main branch

jobs:
  install_nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update package lists
        run: sudo apt-get update

      - name: Install Nginx
        run: sudo apt-get install -y nginx

      - name: Start Nginx service
        run: sudo systemctl start nginx

      - name: Enable Nginx to start on boot
        run: sudo systemctl enable nginx

      - name: Check Nginx status
        run: sudo systemctl status nginx
