name: Install NGINX on AWS Server

on:
  push:
    branches:
      - main  # You can adjust this to any branch you want to trigger the action on.

jobs:
  install_nginx:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code (optional depending on your use case)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up the PEM file as a secret
      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # Step 3: Install NGINX on the AWS instance
      - name: Install NGINX on AWS server
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@54.234.227.52 << 'EOF'
            sudo apt-get update
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
          EOF

      # Clean up the private key file
      - name: Clean up
        run: rm -f private_key.pem
